#!/bin/bash

source ./env/gcloud.env

DOCKERIMAGE="openbridge/gcloud"

docker rm $DOCKERIMAGE
docker run -d --restart=always \
    -e "CLOUDSDK_ACCOUNT_FILE=${CLOUDSDK_ACCOUNT_FILE}" \
    -e "CLOUDSDK_CRON_FILE=${CLOUDSDK_CRON_FILE}" \
    -e "CLOUDSDK_ACCOUNT_EMAIL=${CLOUDSDK_ACCOUNT_EMAIL}" \
    -e "CLOUDSDK_CORE_PROJECT=${CLOUDSDK_CORE_PROJECT}" \
    -e "CLOUDSDK_COMPUTE_ZONE=${CLOUDSDK_COMPUTE_ZONE}" \
    -e "CLOUDSDK_COMPUTE_REGION=${CLOUDSDK_COMPUTE_REGION}" \
    -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
    -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
    -e "BIGQUERY_SQL=${BIGQUERY_SQL}" \
    -e "BIGQUERY_GA_DATASET=${BIGQUERY_GA_DATASET}" \
    -e "GSBUCKET=${GSBUCKET}" \
    -e "S3BUCKET=${S3BUCKET}" \
    -e "LOG_FILE=${LOG_FILE}" \
    "${DOCKERIMAGE}" \
    cron

exit 0
